---
- hosts: all
  become: yes
  tasks:
    - name: "Add apt key Elastic & kibana"
      ansible.builtin.apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: "Install apt thansport https"
      ansible.builtin.apt:
        name: apt-transport-https
        state: present

    - name: "Add Elastic & kibana repository"
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
        state: present

    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: "Install Elastic"
      ansible.builtin.apt:
        name: elasticsearch
        state: present

    - name: "Install Kibana"
      ansible.builtin.apt:
        name: kibana
        state: present

    - name: "Install Logstash"
      ansible.builtin.apt:
        name: logstash
        state: present

    - name: "Install Filebeat"
      ansible.builtin.apt:
        name: filebeat
        state: present

    - name: "Elastic systemd"
      systemd:
        name: elasticsearch
        state: started
        enabled: yes

    - name: "Kibana systemd"
      systemd:
        name: kibana
        state: started
        enabled: yes

    - name: "Config input"
      copy:
        src: /elastic/file/input.conf
        dest: /etc/logstash/conf.d
        owner: root
        group: root
        mode: 0644

    - name: "Config output"
      copy:
        src: /elastic/file/output.conf
        dest: /etc/logstash/conf.d
        owner: root
        group: root
        mode: 0644

    - name: "Config filter"
      copy:
        src: /elastic/file/filter.conf
        dest: /etc/logstash/conf.d
        owner: root
        group: root
        mode: 0644

    - name: "Config filebeat"
      copy:
        src: /elastic/file/filebeat.yml
        dest: /etc/filebeat
        owner: root
        group: root
        mode: 0644

    - name: "Logstash systemd"
      systemd:
        name: logstash
        state: started
        enabled: yes

    - name: "Logstash systemd"
      systemd:
        name: logstash
        state: restarted
        enabled: yes

    - name: "Kibana systemd"
      systemd:
        name: kibana
        state: restarted
        enabled: yes

    - name: "Elastic systemd"
      systemd:
        name: elasticsearch
        state: restarted
        enabled: yes
